parameters:
 - name: variableFiles
   type: object
jobs:
 - job:
   variables:
     - ${{ parameters.variableFiles }}
   steps:
     - checkout: yamltemplate
     - checkout: self
     - task: PowerShell@2  #added comment to PR branch
       inputs:
         targetType: 'inline'
         script: |
           # Write your PowerShell commands here.
           
           Write-Host "Hello World"
           Write-Host "$(Build.SourceBranch)"
           #Write-Host ${{ variables.experiment_name }}
       #  pwsh: true
